org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=hologram_api
mod.name=Hologram API
mod.group=net.ray
mod.version=2.0.2
mod.channel_tag=
mod.authors=ray
mod.contributors=
mod.license=MIT
mod.description=API for client-side in world text rendering.
mod.sources_url=https://github.com/ray22777/hologram-api
mod.issues_url=https://github.com/ray22777/hologram-api/issues


deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=gM6gWVgx
publish.curseforge=1447353
publish.github=false
